; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = 
	https://github.com/bolderflight/units.git
	https://github.com/bolderflight/wmm.git
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	bodmer/TFT_eSPI@^2.5.43
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit ILI9341@^1.6.3
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit LSM303 Accel@^1.1.9
	adafruit/Adafruit LIS2MDL@^2.1.8
monitor_speed = 115200

build_flags =
   ${env.build_flags}
   -D IDF_CCACHE_ENABLE=1
   -Wno-attributes

board_build.cmake_extra_args = -DCCACHE_ENABLE=ON

[platformio]
description = LSM303 with CYD
build_cache_dir = .pio/cache
